"""PR description generation.

Auto-generates a title and body for the PR based on the diff when the
PR was opened without a meaningful description. Updates the PR via the
GitHub API.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from criticai.config import Config
    from criticai.github import GitHubClient

import requests

from criticai.providers.base import get_provider

# PRs with a body shorter than this are considered "empty"
MIN_DESCRIPTION_LENGTH = 20


def maybe_generate_description(
    github: "GitHubClient",
    config: "Config",
    diff: str,
) -> None:
    """Check if the PR has a meaningful description; if not, generate one.

    Only runs on the first review (no existing bot comment), and only if
    the PR body is empty or trivially short.
    """
    pr_data = _fetch_pr_metadata(config)
    if pr_data is None:
        return

    body = (pr_data.get("body") or "").strip()
    if len(body) >= MIN_DESCRIPTION_LENGTH:
        # PR already has a description — don't overwrite
        return

    print("PR has no meaningful description — generating one.")

    prompt = (
        "Based on the following code diff, generate a concise PR description. "
        "Output ONLY a JSON object with two keys:\n"
        '  "title": a short (<72 char) PR title summarizing the change\n'
        '  "body": a 2-5 sentence description of what the PR does and why\n\n'
        "Do not include markdown fencing around the JSON. Output raw JSON only.\n\n"
        f"Diff:\n{diff[:8000]}"
    )
    system = "You are CriticAI. Generate PR descriptions as JSON. No other text."

    try:
        provider = get_provider(config.model, config)
        result = provider.invoke(config.model, system, prompt)

        # Try to parse the JSON
        data = json.loads(result.strip())
        new_title = data.get("title", "").strip()
        new_body = data.get("body", "").strip()

        if not new_body:
            print("Model returned empty description — skipping.")
            return

        # Update the PR
        update_payload = {}
        if new_body:
            update_payload["body"] = (
                f"{new_body}\n\n"
                f"---\n"
                f"<sub>📝 Description generated by CriticAI</sub>"
            )
        # Only update title if current one looks auto-generated
        current_title = pr_data.get("title", "")
        if new_title and len(current_title) < 10:
            update_payload["title"] = new_title

        if update_payload:
            _update_pr(config, update_payload)
            print(f"PR description updated.")

    except Exception as e:
        print(f"Warning: could not generate PR description: {e}")


def _fetch_pr_metadata(config: "Config") -> dict | None:
    """Fetch PR title and body."""
    url = f"https://api.github.com/repos/{config.repository}/pulls/{config.pr_number}"
    try:
        resp = requests.get(url, headers={
            "Authorization": f"Bearer {config.github_token}",
            "Accept": "application/vnd.github+json",
        })
        resp.raise_for_status()
        return resp.json()
    except requests.RequestException as e:
        print(f"Warning: could not fetch PR metadata: {e}")
        return None


def _update_pr(config: "Config", payload: dict) -> None:
    """Update PR title/body via the API."""
    url = f"https://api.github.com/repos/{config.repository}/pulls/{config.pr_number}"
    resp = requests.patch(url, json=payload, headers={
        "Authorization": f"Bearer {config.github_token}",
        "Accept": "application/vnd.github+json",
    })
    resp.raise_for_status()
